# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='username',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
