# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_expense_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
