# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20171218_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='username',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
